<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'unique_id' => '6224007453001',
                'name' => 'برطمان عسل نوارة البرسيم كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'noar-albrsym-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 15:37:28',
                'updated_at' => '2020-01-04 16:59:58',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            1 => 
            array (
                'id' => 2,
                'unique_id' => '6224007453018',
                'name' => 'برطمان عسل نوارة البرسيم نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'noar-albrsym-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 15:49:07',
                'updated_at' => '2020-01-04 17:00:28',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            2 => 
            array (
                'id' => 3,
                'unique_id' => '6224007453025',
                'name' => 'برطمان عسل نوارة البرسيم ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'noar-albrsym-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 15:51:18',
                'updated_at' => '2020-01-04 17:00:47',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            3 => 
            array (
                'id' => 4,
                'unique_id' => '6224007453032',
                'name' => 'برطمان عسل صحراوي كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'shraoy-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 15:58:20',
                'updated_at' => '2020-01-04 17:01:09',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            4 => 
            array (
                'id' => 5,
                'unique_id' => '6224007453049',
                'name' => 'برطمان عسل صحراوي نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'shraoy-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:01:12',
                'updated_at' => '2020-01-04 17:01:25',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            5 => 
            array (
                'id' => 6,
                'unique_id' => '6224007453063',
                'name' => 'برطمان عسل حبة البركة كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:04:21',
                'updated_at' => '2020-01-04 17:01:53',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            6 => 
            array (
                'id' => 7,
                'unique_id' => '6224007453070',
                'name' => 'برطمان عسل حبة البركة نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:08:57',
                'updated_at' => '2020-01-04 17:02:12',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            7 => 
            array (
                'id' => 8,
                'unique_id' => '6224007453087',
                'name' => 'برطمان عسل حبة البركة ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:11:08',
                'updated_at' => '2020-01-04 17:02:31',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            8 => 
            array (
                'id' => 9,
                'unique_id' => '6224007453094',
                'name' => 'برطمان عسل بردفوش كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'brdksh-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:14:11',
                'updated_at' => '2020-01-04 17:03:05',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            9 => 
            array (
                'id' => 10,
                'unique_id' => '6224007453100',
                'name' => 'برطمان عسل بردفوش نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'brdkosh-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:16:54',
                'updated_at' => '2020-01-04 17:03:50',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            10 => 
            array (
                'id' => 11,
                'unique_id' => '6224007453117',
                'name' => 'برطمان عسل بردفوش ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'brdkosh-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:18:48',
                'updated_at' => '2020-01-04 17:04:33',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            11 => 
            array (
                'id' => 12,
                'unique_id' => '6224007453124',
                'name' => 'برطمان عسل موالح كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 16:21:48',
                'updated_at' => '2020-01-04 17:04:50',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            12 => 
            array (
                'id' => 13,
                'unique_id' => '6224007453131',
                'name' => 'برطمان عسل موالح نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:30:34',
                'updated_at' => '2020-01-04 17:05:45',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            13 => 
            array (
                'id' => 14,
                'unique_id' => '6224007453148',
                'name' => 'برطمان عسل موالح ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:33:50',
                'updated_at' => '2020-01-04 17:05:59',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            14 => 
            array (
                'id' => 15,
                'unique_id' => '6224007453209',
            'name' => 'بلح (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'blh-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:36:27',
                'updated_at' => '2019-12-29 17:36:27',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            15 => 
            array (
                'id' => 16,
                'unique_id' => '6224007453216',
            'name' => 'بلح (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'blh-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:38:00',
                'updated_at' => '2019-12-29 17:38:00',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            16 => 
            array (
                'id' => 17,
                'unique_id' => '6224007453308',
                'name' => 'برطمان عسل جبلي سعودي نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-saaody-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:44:08',
                'updated_at' => '2020-01-04 17:07:07',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            17 => 
            array (
                'id' => 18,
                'unique_id' => '6224007453315',
                'name' => 'برطمان عسل جبلي سعودي ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-saaody-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:46:20',
                'updated_at' => '2020-01-04 17:07:26',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            18 => 
            array (
                'id' => 19,
                'unique_id' => '6224007453322',
                'name' => 'برطمان عسل جبلي ليبي نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-lyby-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:47:45',
                'updated_at' => '2020-01-04 17:07:53',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            19 => 
            array (
                'id' => 20,
                'unique_id' => '6224007453339',
                'name' => 'برطمان عسل جبلي ليبي ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-lyby-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:49:04',
                'updated_at' => '2020-01-04 17:08:17',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            20 => 
            array (
                'id' => 21,
                'unique_id' => '6224007453346',
                'name' => 'برطمان عسل جبلي مر حنون نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-mr-hnon-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:53:50',
                'updated_at' => '2020-01-04 17:08:48',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            21 => 
            array (
                'id' => 22,
                'unique_id' => '6224007453353',
                'name' => 'برطمان عسل جبلي مر حنون ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-mr-hnon-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 17:55:32',
                'updated_at' => '2020-01-04 17:09:04',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            22 => 
            array (
                'id' => 23,
                'unique_id' => '6224007453360',
                'name' => 'برطمان عسل جبلي زعتر نصف كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-zaatr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:02:34',
                'updated_at' => '2020-01-04 17:09:32',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            23 => 
            array (
                'id' => 24,
                'unique_id' => '6224007453377',
                'name' => 'برطمان عسل جبلي زعتر ربع كيلو',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-zaatr-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:04:17',
                'updated_at' => '2020-01-04 17:09:49',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            24 => 
            array (
                'id' => 25,
                'unique_id' => '6224007453384',
            'name' => 'جبلي مصري (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-msry-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:05:54',
                'updated_at' => '2020-01-04 17:10:08',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            25 => 
            array (
                'id' => 26,
                'unique_id' => '6224007453391',
            'name' => 'جبلي مصري (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-msry-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:07:35',
                'updated_at' => '2020-01-04 17:10:19',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            26 => 
            array (
                'id' => 27,
                'unique_id' => '6224007453407',
            'name' => 'جبلي مصري (ربع كيلو)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-msry-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:09:24',
                'updated_at' => '2020-01-04 17:10:28',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            27 => 
            array (
                'id' => 28,
                'unique_id' => '6224007453414',
            'name' => 'جبلي بري ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-bry-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:11:08',
                'updated_at' => '2020-01-04 17:10:35',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            28 => 
            array (
                'id' => 29,
                'unique_id' => '6224007453421',
            'name' => 'جبلي بري ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-bry-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:13:10',
                'updated_at' => '2020-01-04 17:11:05',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            29 => 
            array (
                'id' => 30,
                'unique_id' => '6224007453438',
            'name' => 'جبلي بري ( ربع كيلو)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-bry-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:14:25',
                'updated_at' => '2020-01-04 17:11:20',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            30 => 
            array (
                'id' => 31,
                'unique_id' => '6224007453568',
            'name' => 'نوارة البرسيم تصدير (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'noar-albrsym-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:16:00',
                'updated_at' => '2019-12-29 18:16:00',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            31 => 
            array (
                'id' => 32,
                'unique_id' => '6224007453575',
            'name' => 'نواة البرسيم تصدير ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'noa-albrsym-tsdyr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:18:54',
                'updated_at' => '2019-12-29 18:18:54',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            32 => 
            array (
                'id' => 33,
                'unique_id' => '6224007453582',
            'name' => 'موالح تصدير ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:21:29',
                'updated_at' => '2019-12-29 18:21:29',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            33 => 
            array (
                'id' => 34,
                'unique_id' => '6224007453599',
            'name' => 'موالح تصدير ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-tsdyr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:22:39',
                'updated_at' => '2019-12-29 18:22:39',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            34 => 
            array (
                'id' => 35,
                'unique_id' => '6224007453605',
            'name' => 'بردقوش تصدير ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'brdkosh-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:25:36',
                'updated_at' => '2020-01-01 18:26:34',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            35 => 
            array (
                'id' => 36,
                'unique_id' => '6224007453612',
            'name' => 'بردقوش تصدير (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'brdkosh-tsdyr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-29 18:27:01',
                'updated_at' => '2019-12-29 18:27:01',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            36 => 
            array (
                'id' => 37,
                'unique_id' => '6224007453629',
            'name' => 'ألنباتات الطبية (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'alnbatat-altby-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 10:51:39',
                'updated_at' => '2020-01-01 10:05:54',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            37 => 
            array (
                'id' => 38,
                'unique_id' => '6224007453636',
            'name' => 'النباتات الطبية (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'alnbatat-altby-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 10:52:46',
                'updated_at' => '2020-01-01 10:14:36',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            38 => 
            array (
                'id' => 39,
                'unique_id' => '6224007453643',
            'name' => 'صحراوي تصدير (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'shraoy-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 10:54:09',
                'updated_at' => '2019-12-30 10:54:09',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            39 => 
            array (
                'id' => 40,
                'unique_id' => '6224007453650',
            'name' => 'صحراوي تصدير (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'shraoy-tsdyr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 10:57:27',
                'updated_at' => '2019-12-30 10:57:27',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            40 => 
            array (
                'id' => 41,
                'unique_id' => '6224007453667',
            'name' => 'حبة البركة تصدير ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:00:08',
                'updated_at' => '2019-12-30 11:00:08',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            41 => 
            array (
                'id' => 42,
                'unique_id' => '6224007453674',
            'name' => 'حبة البركة تصدير ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:03:39',
                'updated_at' => '2020-01-04 15:48:31',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            42 => 
            array (
                'id' => 43,
                'unique_id' => '6224007453681',
            'name' => 'بلدي تصدير ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'bldy-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:05:42',
                'updated_at' => '2019-12-30 11:05:42',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            43 => 
            array (
                'id' => 44,
                'unique_id' => '6224007453698',
            'name' => 'بلدي تصدير (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'bldy-tsdyr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:07:08',
                'updated_at' => '2020-01-02 14:17:21',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            44 => 
            array (
                'id' => 45,
                'unique_id' => '6224007453544',
            'name' => 'خلطة زيادة الوزن (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'khlt-zyad-alozn-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:09:06',
                'updated_at' => '2019-12-30 11:09:06',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            45 => 
            array (
                'id' => 46,
                'unique_id' => '6224007453551',
            'name' => 'خلطة زيادة الوزن ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'khlt-zyad-alozn-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:10:08',
                'updated_at' => '2019-12-30 11:10:08',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            46 => 
            array (
                'id' => 47,
                'unique_id' => '6224007453230',
            'name' => 'عسل بغذاء الملكات للاطفال ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-bghtha-almlkat-llatfal-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:11:53',
                'updated_at' => '2019-12-30 11:11:53',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            47 => 
            array (
                'id' => 48,
                'unique_id' => '6224007453247',
            'name' => 'عسل بغذاء الملكات للاطفال ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-bghtha-almlkat-llatfal-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:13:28',
                'updated_at' => '2019-12-30 11:13:28',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            48 => 
            array (
                'id' => 49,
                'unique_id' => '6224007453513',
            'name' => 'دبس التمر ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'dbs-altmr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:14:59',
                'updated_at' => '2019-12-30 11:14:59',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            49 => 
            array (
                'id' => 50,
                'unique_id' => '6224007453506',
            'name' => 'عسل بالمكسرات (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-balmksrat-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:16:21',
                'updated_at' => '2019-12-30 11:16:21',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            50 => 
            array (
                'id' => 51,
                'unique_id' => '6224007453179',
            'name' => 'عسل بالمكسرات (ربع كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-balmksrat-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:18:25',
                'updated_at' => '2019-12-30 11:18:25',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            51 => 
            array (
                'id' => 52,
                'unique_id' => '6224007453469',
            'name' => 'عسل الغابات (ربع كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-alghabat-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:19:38',
                'updated_at' => '2019-12-30 11:19:38',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            52 => 
            array (
                'id' => 53,
                'unique_id' => '6224007453162',
            'name' => 'غذاء أمريكي (10جم)',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'ghtha-amryky-10jm',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:22:15',
                'updated_at' => '2019-12-30 11:22:15',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 10,
            ),
            53 => 
            array (
                'id' => 54,
                'unique_id' => '6224007453193',
            'name' => 'غذاء مستورد (5جم)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'ghtha-mstord-5jm',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:23:36',
                'updated_at' => '2019-12-30 11:23:36',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 5,
            ),
            54 => 
            array (
                'id' => 55,
                'unique_id' => '6224007453254',
                'name' => 'كيس جنين القمح',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'kys-jnyn-alkmh',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:26:03',
                'updated_at' => '2019-12-30 11:26:03',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 35,
            ),
            55 => 
            array (
                'id' => 56,
                'unique_id' => '6224007453292',
            'name' => 'جركن صحراوي تصدير (5 كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jrkn-shraoy-tsdyr-5-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:28:37',
                'updated_at' => '2019-12-30 11:28:37',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 5000,
            ),
            56 => 
            array (
                'id' => 57,
                'unique_id' => '6224007453452',
            'name' => 'جركن بركة تصدير ( 5 كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jrkn-brk-tsdyr-5-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:30:11',
                'updated_at' => '2019-12-30 11:30:11',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 5000,
            ),
            57 => 
            array (
                'id' => 58,
                'unique_id' => '6224007453483',
                'name' => 'Power Honey',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'power-honey',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:32:45',
                'updated_at' => '2020-01-04 13:45:41',
                'deleted_at' => NULL,
                'archive' => 1,
                'weight' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'unique_id' => '6224007453490',
                'name' => 'غذاء بلدي 5 جم',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'ghtha-bldy-5-jm',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:34:13',
                'updated_at' => '2019-12-30 11:34:13',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 5,
            ),
            59 => 
            array (
                'id' => 60,
                'unique_id' => '6224007453728',
                'name' => 'أعشاب تخسيس',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'aaashab-tkhsys',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:36:39',
                'updated_at' => '2020-01-04 19:02:29',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'unique_id' => '6224007453735',
                'name' => 'اعشاب قولون',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'aaashab-kolon',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:37:58',
                'updated_at' => '2019-12-31 16:09:33',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'unique_id' => '6224007453742',
                'name' => 'اعشاب سكر',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'aaashab-skr',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:39:17',
                'updated_at' => '2020-01-01 14:51:14',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'unique_id' => '6224007453759',
                'name' => 'اعشاب كحة',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'aaashab-kh',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:41:09',
                'updated_at' => '2020-01-01 14:51:14',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'unique_id' => '6224007453766',
                'name' => 'أعشاب الاملاح و الحصوات',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'aaashab-alamlah-o-alhsoat',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:49:33',
                'updated_at' => '2019-12-31 12:40:15',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'unique_id' => '6224007453780',
                'name' => 'كيس حبوب اللقاح',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'kys-hbob-allkah',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:50:35',
                'updated_at' => '2019-12-30 11:50:35',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'unique_id' => '6224007453797',
                'name' => 'بروبليس',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'broblys',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:52:02',
                'updated_at' => '2019-12-30 11:52:02',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'unique_id' => '6224007453803',
                'name' => 'جنسنج أبيض',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jnsnj-abyd',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:53:30',
                'updated_at' => '2019-12-30 11:53:30',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            67 => 
            array (
                'id' => 68,
                'unique_id' => '6224007453810',
                'name' => 'طلع نخل ',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'tlaa-nkhl',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:55:14',
                'updated_at' => '2019-12-30 11:55:14',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            68 => 
            array (
                'id' => 69,
                'unique_id' => '6224007453827',
                'name' => 'جنسنج احمر ',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jnsnj-ahmr',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 11:56:37',
                'updated_at' => '2019-12-30 11:56:37',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1,
            ),
            69 => 
            array (
                'id' => 70,
                'unique_id' => '6224007453834',
            'name' => 'علبة شمع ( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aalb-shmaa-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:35:02',
                'updated_at' => '2019-12-30 12:35:02',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            70 => 
            array (
                'id' => 71,
                'unique_id' => '6224007453841',
            'name' => 'جركن موالح تصدير ( 5 كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'jrkn-moalh-tsdyr-5-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:36:58',
                'updated_at' => '2020-01-04 09:22:59',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 5000,
            ),
            71 => 
            array (
                'id' => 72,
                'unique_id' => '6224007453865',
                'name' => 'نوارة بدون استيكر',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'noar-bdon-astykr',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:39:51',
                'updated_at' => '2020-01-04 09:22:59',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            72 => 
            array (
                'id' => 73,
                'unique_id' => '6224007453872',
            'name' => 'نوارة بدون ستيكر (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'noar-bdon-stykr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:41:28',
                'updated_at' => '2020-01-04 13:45:48',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            73 => 
            array (
                'id' => 74,
                'unique_id' => '6224007453889',
            'name' => 'نوارة بدون استيكر (ربع كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'noar-bdon-astykr-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:45:26',
                'updated_at' => '2019-12-30 12:45:26',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            74 => 
            array (
                'id' => 75,
                'unique_id' => '6224007453896',
            'name' => 'صحراوي بدون استيكر (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'shraoy-bdon-astykr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:47:11',
                'updated_at' => '2019-12-30 12:47:11',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            75 => 
            array (
                'id' => 76,
                'unique_id' => '6224007453902',
            'name' => 'صحراوي بدون استيكر (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'shraoy-bdon-astykr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:49:08',
                'updated_at' => '2019-12-30 12:49:08',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            76 => 
            array (
                'id' => 77,
                'unique_id' => '6224007453919',
            'name' => 'حبة البركة  بدون استيكر ( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk-bdon-astykr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:50:33',
                'updated_at' => '2019-12-30 12:50:33',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            77 => 
            array (
                'id' => 78,
                'unique_id' => '6224007453926',
            'name' => 'حبة البركة بدون استيكر (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'hb-albrk-bdon-astykr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:52:52',
                'updated_at' => '2019-12-30 12:52:52',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            78 => 
            array (
                'id' => 79,
                'unique_id' => '6224007453933',
            'name' => 'بردقوش بدون استيكر( كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'brdkosh-bdon-astykr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:55:08',
                'updated_at' => '2019-12-30 12:55:08',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            79 => 
            array (
                'id' => 80,
                'unique_id' => '6224007453940',
            'name' => 'بردقوش بدون استيكر( نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'brdkosh-bdon-astykr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:56:28',
                'updated_at' => '2019-12-30 12:56:28',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            80 => 
            array (
                'id' => 81,
                'unique_id' => '6224007453957',
            'name' => 'موالح بدون استيكر (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-bdon-astykr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:58:05',
                'updated_at' => '2019-12-30 12:58:05',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            81 => 
            array (
                'id' => 82,
                'unique_id' => '6224007453964',
            'name' => 'موالح بدون استيكر (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'moalh-bdon-astykr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 12:59:13',
                'updated_at' => '2019-12-30 12:59:13',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            82 => 
            array (
                'id' => 83,
                'unique_id' => '6224007453971',
            'name' => 'بلح بدون استيكر (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'blh-bdon-astykr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:00:19',
                'updated_at' => '2019-12-30 13:00:19',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            83 => 
            array (
                'id' => 84,
                'unique_id' => '6224007453988',
            'name' => 'بلح بدون استيكر (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'blh-bdon-astykr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:01:33',
                'updated_at' => '2019-12-30 13:01:33',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            84 => 
            array (
                'id' => 85,
                'unique_id' => '6224007453155',
            'name' => 'عسل بالشمع تصدير (كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-balshmaa-tsdyr-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:03:06',
                'updated_at' => '2019-12-30 13:03:06',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 1000,
            ),
            85 => 
            array (
                'id' => 86,
                'unique_id' => '6224007453711',
            'name' => 'عسل بالشمع تصدير (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'aasl-balshmaa-tsdyr-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:04:21',
                'updated_at' => '2019-12-30 13:04:21',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            86 => 
            array (
                'id' => 87,
                'unique_id' => '6224007453858',
            'name' => 'جركن نوارة تصدير (5 كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jrkn-noar-tsdyr-5-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:06:20',
                'updated_at' => '2019-12-30 13:06:20',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 5000,
            ),
            87 => 
            array (
                'id' => 88,
                'unique_id' => '6224007453445',
            'name' => 'جبلي سدر حضرمي (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-sdr-hdrmy-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:08:32',
                'updated_at' => '2019-12-30 13:08:32',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 500,
            ),
            88 => 
            array (
                'id' => 89,
                'unique_id' => '6224007453186',
            'name' => 'جبلي سدر حضرمي (ربع  كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-sdr-hdrmy-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:09:36',
                'updated_at' => '2019-12-30 13:09:36',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => 250,
            ),
            89 => 
            array (
                'id' => 90,
                'unique_id' => '6224007453704',
            'name' => 'جبلي سدر دوعني (نصف كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jbly-sdr-doaany-nsf-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:12:18',
                'updated_at' => '2019-12-30 13:12:18',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'unique_id' => '6224007453520',
            'name' => 'جبلي سدر دوعني (ربع كيلو)',
                'category_id' => 1,
                'subcategory_id' => 1,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'jbly-sdr-doaany-rbaa-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:17:41',
                'updated_at' => '2020-01-04 09:23:00',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'unique_id' => '6224007453995',
                'name' => 'تركيبة بشرة ',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'trkyb-bshr',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:18:51',
                'updated_at' => '2019-12-30 13:18:51',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'unique_id' => '6224007453056',
                'name' => 'أعشاب الجنس',
                'category_id' => 1,
                'subcategory_id' => 2,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'aaashab-aljns',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:20:04',
                'updated_at' => '2020-01-01 14:51:14',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'unique_id' => '6224007400001',
                'name' => 'بلح 800 جرام',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => '30',
                'status' => 1,
                'slug' => 'blh-800-jram',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:24:32',
                'updated_at' => '2019-12-31 14:49:28',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'unique_id' => '6224007400002',
                'name' => 'بلح باللوز 400 جم',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'blh-balloz-400-jm',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:25:57',
                'updated_at' => '2020-01-01 18:19:10',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'unique_id' => '6224007400003',
                'name' => 'غذاء امريكي 5 جم',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'ghtha-amryky-5-jm',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:27:29',
                'updated_at' => '2019-12-30 13:27:29',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'unique_id' => '6224007400004	',
                'name' => 'شمع براويز بالجرام',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 0,
                'slug' => 'shmaa-braoyz-baljram',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:34:23',
                'updated_at' => '2020-01-04 16:59:13',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'unique_id' => '6224007400005	',
            'name' => 'صفيحة نورة (25 كيلو)',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'sfyh-nor-25-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:36:21',
                'updated_at' => '2019-12-30 13:36:21',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'unique_id' => '6224007400006	',
                'name' => 'صفيحة صحراوي 25 كيلو',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'sfyh-shraoy-25-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:37:52',
                'updated_at' => '2019-12-30 13:37:52',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'unique_id' => '6224007400007	',
                'name' => 'صفيحة حبة البركة 25 كيلو',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'sfyh-hb-albrk-25-kylo',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:39:09',
                'updated_at' => '2019-12-30 13:39:09',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'unique_id' => '6224007400008	',
                'name' => 'بلح بالكاجو 400 جم',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'blh-balkajo-400-jm',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:40:46',
                'updated_at' => '2019-12-30 13:40:46',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'unique_id' => '6224007400009	',
                'name' => 'زيت إطالة',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'zyt-etal',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:43:04',
                'updated_at' => '2019-12-30 13:43:04',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'unique_id' => '6224007400010	',
                'name' => 'زيت الفرد',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'zyt-alfrd',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:44:42',
                'updated_at' => '2019-12-30 13:44:42',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'unique_id' => '6224007400011	',
                'name' => 'زيت المعالج',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'zyt-almaaalj',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:46:22',
                'updated_at' => '2019-12-30 13:46:22',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'unique_id' => '6224007400012	',
                'name' => 'جنين القمح علب',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'jnyn-alkmh-aalb',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:47:52',
                'updated_at' => '2019-12-30 13:47:52',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'unique_id' => '6224007400013	',
                'name' => 'معالق خشب',
                'category_id' => 2,
                'subcategory_id' => 3,
                'discount' => NULL,
                'status' => 1,
                'slug' => 'maaalk-khshb',
                'quantity' => 0,
                'num_of_orders' => NULL,
                'created_at' => '2019-12-30 13:50:36',
                'updated_at' => '2019-12-30 13:50:36',
                'deleted_at' => NULL,
                'archive' => 0,
                'weight' => NULL,
            ),
        
        ));
        
        
    }
}